// app/cookTimes.ts
// Cook times in MINUTES.
// This is the actual cook/prep time once you're at the client's location.
// Anything not listed here falls back to DEFAULT_COOK_MINUTES.
// Edit these numbers as you learn your real times.

export const DEFAULT_COOK_MINUTES = 15;

export const COOK_TIMES: Record<string, number> = {
  // --- BREAKFAST ---
  'eggs-boiled': 15,
  'eggs-fried': 5,
  'eggs-scrambled': 5,
  'eggs-omelette': 8,
  'eggs-omelette-pockets': 10,
  'french-toast': 10,
  'pancakes': 10,
  'waffles': 10,
  'stuffed-waffle': 15,
  'bacon': 10,
  'breakfast-sausage': 10,
  'breakfast-sausage-patty': 10,
  'chunks': 20,
  'diced': 15,
  'hash-brown': 10,
  'toast': 5,
  'english-muffin': 5,
  'biscuit': 5,
  'muffin': 5,
  'breakfast-sandwich-club': 15,
  'breakfast-sandwich-muffin': 15,
  'fried-steak-beef': 20,
  'fried-steak-chicken': 20,
  'breakfast-burrito': 15,
  'breakfast-yogurt': 3,
  'apple': 2,
  'banana': 2,
  'lime': 1,
  'orange': 1,

  // --- SANDWICHES ---
  'classic-sandwich': 10,
  'club-sandwich': 15,
  'half-hoagie': 10,
  'submarine': 15,
  'grilled-cheese': 10,
  'panini': 12,
  'hot-dog': 10,
  'link': 10,
  'submarine-sausage': 15,
  'burger': 20,
  'sliders': 20,
  'sandwiches-gyro': 20,
  'sandwiches-savory-stuffed-waffle': 20,

  // --- BIRDS ---
  'whole': 30,
  'half': 20,
  'drum': 15,
  'thigh': 15,
  'breast': 20,
  'wings': 20,
  'birds-fried-chicken': 30,
  'birds-fried-turkey': 60,
  'birds-steamed-breasts': 20,
  'steamed-breast-chicken': 20,
  'steamed-breast-turkey': 20,

  // --- SEAFOOD ---
  'battered': 15,
  'sauteed': 15,
  'steamed': 20,
  'dungeness': 20,
  'snow': 15,
  'king': 25,
  'seared-lobster-tail': 15,
  'steamed-lobster-tail': 20,
  'large-lobster-tail': 25,
  'battered-shrimp': 10,
  'sauteed-shrimp': 10,
  'steamed-shrimp': 10,

  // --- FRIED SIDES ---
  'fries-potato': 8,
  'fries-curlies': 8,
  'fries-wedges': 12,
  'fries-zu-fries': 8,
  'fries-zu-curlies': 8,
  'popcorn-chicken': 12,
  'popcorn-shrimp': 12,
  'popcorn-flower': 12,
  'onions-blossom': 15,
  'onions-rings': 10,
  'fried-sides-jalapeno-poppers': 10,
  'fried-sides-mini-pockets': 12,

  // --- AIR-FRIED ---
  'birds-air-fried-chicken': 45,
  'birds-air-fried-turkey': 60,

  // --- LATIN AMERICA ---
  'latin-america-burrito': 15,
  'latin-america-quesadilla': 10,
  'latin-america-enchiladas': 25,
  'latin-taco': 10,
  'latin-taco-trio': 15,
  'latin-taco-pack': 25,
  'latin-taco-party': 40,
  'latin-taco-party-fiesta-grande': 60,
  'latin-america-nachos': 15,

  // --- ASIAN ---
  'chow-mein': 20,
  'stir-fry': 20,
  'citrus-glazed-chicken': 25,
  'wonton-roll': 10,
  'spring-roll': 10,

  // --- BEEF ---
  'beef-battered': 20,
  'beef-ribeye': 25,
  'beef-chunks': 20,
  'beef-ground-beef': 20,

  // --- VEGGIES ---
  'veggies-salad-garden': 10,
  'veggies-salad-chefs': 15,
  'veggies-sauteed': 15,
  'veggies-steamed': 15,

  // --- SOUPS & STEWS ---
  'soups-hot-pot': 60,
  'soups-noodle': 30,
  'soups-ramen': 30,
  'soups-stew-gumbo': 120,
  'soups-stew-stew': 120,
  'soups-chili-quick': 60,
  'soups-chili-slow': 240,
  'soups-jambalaya': 60,

  // --- SIDES ---
  'sides-mac': 20,
  'sides-alfredo': 20,
  'sides-garlic': 15,
  'sides-rice': 20,
  'sides-fresh-fruit-cup': 10,
  'sides-breads-roll': 5,
  'sides-breads-pita': 5,
  'sides-breads-slice': 5,
  'sides-breads-bun': 5,

  // --- JR. DISHES ---
  'jr-hot-dog': 10,
  'jr-burger': 15,
  'jr-grilled-cheese': 10,
  'jr-chicken-fingers': 15,
  'jr-fries': 8,
  'jr-curlies': 8,
  'jr-quesadilla': 10,
  'jr-soft-taco': 10,
  'jr-mac-cheese': 20,
  'jr-fruit-cup': 5,
  'jr-sticks-dip': 10,

  // --- TREATS ---
  'treats-candied-fruit-cup': 10,
  'treats-pancake-taco': 15,
  'treats-stuffed-waffle': 20,
  'treats-dessert-dumplings': 15,

  // --- FLAMED ---
  'flamed-big-beef': 60,
  'flamed-tri-tip': 60,
  'flamed-tomahawk': 45,
  'flamed-ribs': 90,
  'flamed-short': 90,
  'flamed-flanken': 60,
  'flamed-lamb': 60,
  'flamed-chicken': 60,
  'flamed-spatchcock': 60,
  'flamed-half': 45,
  'flamed-drums': 30,
  'flamed-thighs': 30,
  'flamed-breasts': 30,
  'flamed-wings': 30,
  'flamed-stuffed-breasts': 45,
  'stuffed-chicken': 45,
  'stuffed-turkey': 45,
  'flamed-fish': 30,
  'flamed-halibut': 30,
  'flamed-snapper': 30,
  'flamed-shrimp': 15,
  'flamed-burgers': 20,
  'flamed-baked-cabbage': 60,
  'flamed-veggies': 30,
  'flamed-course': 30,
  'flamed-cut': 20,
  'flamed-combo': 30,
  'flamed-baked-potatoes': 60,
  'flamed-standard': 60,
  'flamed-hasselback': 75,
  'flamed-stuffed-peppers': 45,
  'flamed-bell': 45,
  'flamed-jalapeno': 30,

  // --- BRAISED ---
  'braised-beef': 180,
  'braised-pot-roast': 180,
  'braised-short-ribs': 180,
  'braised-oxtails': 180,
  'braised-goat-chunks': 180,
  'braised-lamb': 180,
  'braised-lamb-shank': 180,
  'braised-lamb-loin-chops': 120,
  'braised-chicken': 120,
  'braised-apples': 45,

  // --- ROTISSERIE ---
  'rotisserie-beef': 180,
  'rotisserie-prime-rib': 180,
  'rotisserie-beef-roast': 150,
  'rotisserie-lamb': 150,
  'rotisserie-lamb-leg': 150,
  'rotisserie-lamb-boneless': 120,
  'rotisserie-lamb-shank': 180,
  'rotisserie-chicken': 90,
  'rotisserie-chicken-whole': 90,
  'rotisserie-chicken-hen': 75,
  'rotisserie-turkey': 180,
  'rotisserie-turkey-whole': 180,
  'rotisserie-turkey-half': 120,
  'rotisserie-fish': 45,
  'rotisserie-fish-whole': 45,
  'rotisserie-fish-fillet': 30,
  'rotisserie-cabbage': 90,
  'rotisserie-pineapple': 30,
  'rotisserie-kebabs': 30,

  // --- SMOKED ---
  'smoked-beef': 720,
  'smoked-packer-brisket': 720,
  'smoked-center-brisket': 600,
  'smoked-sirloin-roast': 480,
  'smoked-tomahawk': 360,
  'smoked-oxtails': 300,
  'smoked-chicken': 240,
  'smoked-spatchcock': 240,
  'smoked-half': 240,
  'smoked-tomahawk-leg': 240,
  'smoked-wings': 180,
  'smoked-turkey': 300,
  'smoked-turkey-spatchcock': 300,
  'smoked-turkey-drums': 240,
  'smoked-turkey-thighs': 240,
  'smoked-turkey-wings': 240,
  'smoked-salmon-fillet': 180,
  'smoked-lobster-tail': 120,

  // --- BEVERAGES ---
  'beverages-water': 1,
  'beverages-water-spring': 1,
  'beverages-water-infused': 15,
  'beverages-lemonade': 15,
  'beverages-dirty-limeade': 15,
  'beverages-smoothie': 10,
};